### ISSUE TITLE
Waiting for League to start

### ISSUE THREAD

**Issue by kazene** [Pupix/rift-explorer#27] opened 2019-01-15 12:06 UTC
Hi, I'm from Taiwan server and i found that rift explorer can't recognize my client and stay at Waiting for League to start

1. both rift-explorer and league is run by admin, LeagueClient, LeagueClientUx, LeagueClientUxRender all set to run by admin

2. system.yaml added enable_swagger: true

like this:
---
enable_swagger: true
app:
  app_name: LeagueClient
  bugs

3. tried #3 using LeagueClient.exe --no-rads is not working .
4. both rift explorer and league is in C drive.
5. WMIC PROCESS WHERE name='LeagueClientUx.exe' GET commandline :

C:/Garena/Games/32775/LeagueClient/LeagueClientUx.exe "--locale=zh_TW" "--server
s.chat.chat_host=chattw1.lol.garenanow.com" "--servers.lcds.lcds_host=prodtw1.lo
l.garenanow.com" "--servers.lcds.login_queue_url=https://lqtw1.lol.garenanow.com
/login-queue/rest/queues/lol" "--region=TW" "--parent-client=GarenaPC" "--no-rad
s" "--remoting-auth-token=39Svy0AnSceoIS9CN79UTA" "--app-port=51974" "--install-
directory=C:\Garena\Games\32775\LeagueClient" "--app-name=LeagueClient" "--ux-na
me=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClie
nt Logs" "--bugsplat-name=league_client_riotgames_com" "--bugsplat-platform-id=T
W_GarenaPC" "--app-log-file-path=C:/Garena/Games/32775/Game/Logs/LeagueClient Lo
gs/2019-01-15T20-10-10_15624_LeagueClient.log" "--app-pid=15624" "--no-proxy-ser
ver"

Please help, thanks.

**Comment by Pupix** [comment] 2019-01-15 19:10
Strange. Whenever there's been an error like this it was because of the admin right which Garena applies automatically.

Are you actually running rift explorer with  `Run as Administrator` or just ticked the box in properties?
If you just ticked the box then try to force it by using `Run as Admin` see if it does anything.

**Comment by Pupix** [comment] 2019-01-16 12:16
Is there a file called `lockfile` in `C:\Garena\Games\32775\LeagueClient` after you start the league client?

**Comment by Pupix** [comment] 2019-01-17 10:03
Do you happen to have multiple League of Legends installed? One of which is in `'C:\Riot Games\League of Legends` ?

**Comment by kazene** [comment] 2019-01-17 10:20
The game was installed in D drive first, but rift explorer is not working so i uninstalled it.
after that i installed again to C drive yesterday and totally only one league of legends installed.

**Comment by Remlas** [comment] 2019-01-24 12:36
Same problem on EUNE, but only on one computer - on two another computers working without any problems. Also, my app written in Python works on all computers. So it's somethink from rift-explorer side.

**Comment by Remlas** [comment] 2019-01-24 21:01
Solution for my problem: reinstall League. I had it installed (not just copied) on D drive (in directory like D:\Program Files (x86)\Riot Games\League of Legends). Unistalled, installed on C:\Riot Games\... and it works.
I had swagger enabled, but anyway it was "waiting for league to start". Because I fixed problem by myself I may not reproduce this. Are there any rift-explorer logs which may help you?

**Comment by Pupix** [comment] 2019-01-24 21:11
Doubt any logs would help since it couldn't find the League Client. I'll move my local installation on different drives and see if the problem comes up again.

In the meantime I'll close this if the solution is just moving the installation on different drives.

**Comment by kazene** [comment] 2019-01-25 03:34
actually i've tried to install on different drives, but both C and D is not working(uninstall and install, not just move the directory)

**Comment by Pupix** [comment] 2019-01-25 10:38
I am really at a loss for words. It's very strange that it doesn't work. Have you tried other clients? Like the NA or EUW/N ones?

**Comment by KilianB** [comment] 2019-01-28 10:32
Since this piece of code is responsible to pick up the client: 
https://github.com/Pupix/rift-explorer/blob/5281804d6e3cdf51e225ec4a2a9425ba05464294/util.js
@kazene , can you make sure that the preconditions are met?

Since you have already said that WMIC finds  `LeagueClientUx.exe` in your process the next likely cause is that either `getLCUPathFromProcess()` does not get called or `IS_WIN` resolves to false. 

Can you throw in a few debug statements and see where the program gets stuck?

**Comment by Pupix** [comment] 2019-04-18 22:24
Closed for inactivity

**Closed by Pupix** 2019-04-18 22:24 UTC
