### ISSUE TITLE
Does not work on 32-bit

### ISSUE THREAD

**Issue by yusufcorlu** [Pupix/rift-explorer#97] opened 2019-12-04 17:17 UTC
Is there anyone who can help me use 32-bit Rift Explorer?

**Comment by yusufcorlu** [comment] 2019-12-04 19:10
Can someone please explain in detail how to do it for 32-bit? @Pupix @RayZz-

**Comment by RayZz-** [comment] 2019-12-05 12:06
Duplicate of #32.

**Comment by RayZz-** [comment] 2019-12-05 12:07
Currently rift-explorer does not support 32 bit however it is possible to build it using the instructions in the README.md if the repository

**Comment by yusufcorlu** [comment] 2019-12-05 12:11
The instructions in the README.md file are not really understandable @RayZz-

**Comment by RayZz-** [comment] 2019-12-15 19:23
I'm sorry about that but for now like I have said previously we do not support 32 bit systems so there is not much we can help aside from asking you to build it from the source code. I'm closing this as we do not really intend to ever support 32 bit systems.

**Closed by RayZz-** 2019-12-15 19:23 UTC
